apiVersion: v1
kind: Namespace
metadata:
  name: devops-l3gl
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-l3gl
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # rootpassword
  MYSQL_PASSWORD: cHJvZHVjdHBhc3N3b3Jk # productpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: devops-l3gl
data:
  MYSQL_DATABASE: productdb
  MYSQL_USER: productuser
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: devops-l3gl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-l3gl
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devops-l3gl
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
