global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'product-api'
    metrics_path: '/l3gl/actuator/prometheus'
    static_configs:
      # L'IP doit correspondre à l'IP de la VM1 sur laquelle tourne le Product API
      - targets: ['192.168.239.10:80']
